import { StyleSheet } from "react-native";
import { FONTS, SPACING } from "../../models/constants";

export default StyleSheet.create({
  poster: {
    width: "100%",
    minHeight: 690,
    borderWidth: 1,
    padding: SPACING.large,
    justifyContent: "space-between",
  },
  header: {
    alignItems: "center",
    marginBottom: SPACING.medium,
  },
  appMark: {
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.small,
    paddingVertical: 8,
  },
  appIcon: {
    width: 34,
    height: 34,
  },
  appName: {
    fontSize: FONTS.large,
    marginLeft: SPACING.extraSmall,
    fontWeight: "900",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: SPACING.small,
  },
  kicker: {
    flexShrink: 1,
    fontSize: FONTS.small,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  range: {
    flexShrink: 1,
    fontSize: FONTS.small,
    fontWeight: "700",
    textAlign: "right",
    textTransform: "uppercase",
  },
  divider: {
    width: "100%",
    height: 4,
    marginVertical: SPACING.medium,
  },
  festivalName: {
    fontSize: 44,
    lineHeight: 47,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: SPACING.extraSmall,
    textTransform: "uppercase",
  },
  meta: {
    fontSize: FONTS.medium,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  imageStrip: {
    flexDirection: "row",
    justifyContent: "center",
    columnGap: SPACING.extraSmall,
    marginVertical: SPACING.medium,
  },
  imageCard: {
    width: 92,
    height: 92,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  artistImage: {
    width: "100%",
    height: "100%",
  },
  initials: {
    fontSize: FONTS.large,
    fontWeight: "900",
  },
  lineup: {
    width: "100%",
    borderWidth: 1,
    alignItems: "center",
    rowGap: 5,
    paddingHorizontal: SPACING.small,
    paddingVertical: SPACING.medium,
  },
  lineupLabel: {
    fontSize: FONTS.small,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  headliner: {
    width: "100%",
    fontSize: 33,
    lineHeight: 37,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  secondaryLineup: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: SPACING.small,
  },
  secondaryArtist: {
    maxWidth: "50%",
    paddingHorizontal: SPACING.extraSmall,
    paddingVertical: 3,
  },
  secondaryName: {
    fontSize: FONTS.mediumLarge,
    lineHeight: 22,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  supportingLineup: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: SPACING.small,
  },
  supportingArtist: {
    maxWidth: "33%",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  supportingName: {
    fontSize: FONTS.smallMedium,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
    textTransform: "uppercase",
  },
  genres: {
    fontSize: FONTS.small,
    fontWeight: "800",
    textAlign: "center",
    marginTop: SPACING.medium,
    textTransform: "uppercase",
  },
  footer: {
    alignItems: "center",
    rowGap: SPACING.small,
    marginTop: SPACING.large,
  },
  generatedBy: {
    fontSize: FONTS.small,
    fontWeight: "700",
    textAlign: "center",
  },
});
